export const dummy = [
  {
    _id: "emp001",
    profile: "https://randomuser.me/api/portraits/women/21.jpg",
    name: "Jane Copper",
    position: "Full Time",
    department: "Designer",
    task: "Dashboard Home page Alignment",
    status: "Present",
  },
  {
    _id: "emp002",
    profile: "https://randomuser.me/api/portraits/men/22.jpg",
    name: "Arlene McCoy",
    position: "Full Time",
    department: "Designer",
    task: "Dashboard Login page design, Dashboard Home page design",
    status: "Present",
  },
  {
    _id: "emp003",
    profile: "https://randomuser.me/api/portraits/men/23.jpg",
    name: "Cody Fisher",
    position: "Senior",
    department: "Backend Development",
    task: "--",
    status: "Absent",
  },
  {
    _id: "emp004",
    profile: "https://randomuser.me/api/portraits/women/24.jpg",
    name: "Janney Wilson",
    position: "Junior",
    department: "Backend Development",
    task: "Dashboard login page integration",
    status: "Present",
  },
  {
    _id: "emp005",
    profile: "https://randomuser.me/api/portraits/men/25.jpg",
    name: "Leslie Alexander",
    position: "Team Lead",
    department: "Human Resource",
    task: "4 scheduled interview, Sorting of resumes",
    status: "Present",
  },
  {
    _id: "emp006",
    profile: "https://randomuser.me/api/portraits/women/26.jpg",
    name: "Sophia Patel",
    position: "Intern",
    department: "Marketing",
    task: "Market research on competitors",
    status: "Absent",
  },
  {
    _id: "emp007",
    profile: "https://randomuser.me/api/portraits/men/27.jpg",
    name: "Rahul Verma",
    position: "Full Time",
    department: "IT Support",
    task: "Resolved 12 support tickets",
    status: "Present",
  },
  {
    _id: "emp008",
    profile: "https://randomuser.me/api/portraits/women/28.jpg",
    name: "Emily Johnson",
    position: "Senior",
    department: "Design",
    task: "Landing page redesign, Mobile app wireframe",
    status: "Present",
  },
  {
    _id: "emp009",
    profile: "https://randomuser.me/api/portraits/men/29.jpg",
    name: "Michael Brown",
    position: "Full Time",
    department: "Finance",
    task: "Quarterly budget analysis",
    status: "Absent",
  },
  {
    _id: "emp010",
    profile: "https://randomuser.me/api/portraits/women/30.jpg",
    name: "Olivia Green",
    position: "Team Lead",
    department: "Operations",
    task: "Team sprint planning, Daily standup reports",
    status: "Present",
  },
];

