export const dummy = [
  {
    _id: "1",
    profile: "https://randomuser.me/api/portraits/men/11.jpg",
    name: "Cody Fisher",
    designation: "Senior Backend Developer",
    date: "2024-09-08",
    reason: "Visiting House",
    status: "Approved",
    docs: "leave_doc_1.pdf",
  },
  {
    _id: "2",
    profile: "https://randomuser.me/api/portraits/women/21.jpg",
    name: "Jane Cooper",
    designation: "Frontend Engineer",
    date: "2024-09-10",
    reason: "Medical Checkup",
    status: "Pending",
    docs: "leave_doc_2.pdf",
  },
  {
    _id: "3",
    profile: "https://randomuser.me/api/portraits/men/31.jpg",
    name: "Robert Fox",
    designation: "DevOps Engineer",
    date: "2024-09-12",
    reason: "Family Function",
    status: "Rejected",
    docs: "leave_doc_3.pdf",
  },
  {
    _id: "4",
    profile: "https://randomuser.me/api/portraits/women/41.jpg",
    name: "Kristin Watson",
    designation: "HR Manager",
    date: "2024-09-15",
    reason: "Conference Attending",
    status: "Approved",
    docs: "leave_doc_4.pdf",
  },
  {
    _id: "5",
    profile: "https://randomuser.me/api/portraits/men/51.jpg",
    name: "Jacob Jones",
    designation: "UI/UX Designer",
    date: "2024-09-18",
    reason: "Personal Work",
    status: "Pending",
    docs: "leave_doc_5.pdf",
  },
  {
    _id: "6",
    profile: "https://randomuser.me/api/portraits/women/61.jpg",
    name: "Savannah Nguyen",
    designation: "QA Engineer",
    date: "2024-09-20",
    reason: "Sick Leave",
    status: "Approved",
    docs: "leave_doc_6.pdf",
  },
  {
    _id: "7",
    profile: "https://randomuser.me/api/portraits/men/71.jpg",
    name: "Guy Hawkins",
    designation: "Full Stack Developer",
    date: "2024-09-23",
    reason: "Vacation",
    status: "Pending",
    docs: "leave_doc_7.pdf",
  },
  {
    _id: "8",
    profile: "https://randomuser.me/api/portraits/women/81.jpg",
    name: "Courtney Henry",
    designation: "Project Manager",
    date: "2024-09-25",
    reason: "Family Trip",
    status: "Approved",
    docs: "leave_doc_8.pdf",
  },
  {
    _id: "9",
    profile: "https://randomuser.me/api/portraits/men/91.jpg",
    name: "Jerome Bell",
    designation: "Cloud Architect",
    date: "2024-09-27",
    reason: "Work from Home",
    status: "Rejected",
    docs: "leave_doc_9.pdf",
  },
  {
    _id: "10",
    profile: "https://randomuser.me/api/portraits/women/12.jpg",
    name: "Leslie Alexander",
    designation: "Business Analyst",
    date: "2024-09-30",
    reason: "Maternity Checkup",
    status: "Pending",
    docs: "leave_doc_10.pdf",
  },
];
